import Base64Heler from "./libs/Base64";
import RegHelper from "./libs/Reg";
import StorageHelper from "./libs/Storage";
import StringUtilHelper from "./libs/StringUtil";
import UniHelper from "./libs/UniHelper";
export const Base64=Base64Heler;
export const Reg = RegHelper;
export const Storage = StorageHelper;
export const StringUtil = StringUtilHelper;
export const Uniapp = UniHelper;